In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

from food_manager.api import Api
from food_manager.db import SessionLocal

E:\dev\food-manager\src\food_manager\db\__init__.py:22: UserWarning: Using in-memory database. This is not suitable for production.
  warnings.warn("Using in-memory database. This is not suitable for production.")

In [3]:
os.getenv("DATABASE_URL")

In [4]:
session = SessionLocal()

api = Api(session=session)
api.drop_tables()
api.create_tables()

api.get_all_food_items()

2024-11-30 13:59:55.754 | INFO     | food_manager.api:create_tables:204 - Created all tables in the database.
2024-11-30 13:59:55.755 | INFO     | food_manager.api:drop_tables:210 - Dropped all tables in the database.
2024-11-30 13:59:55.757 | INFO     | food_manager.api:create_tables:204 - Created all tables in the database.
2024-11-30 13:59:55.763 | INFO     | food_manager.api:get_all_food_items:197 - Retrieved all food items from the database.

Empty DataFrame
Columns: [id, name, quantity, date_added, user_id]
Index: []

In [5]:
try:
    api.create_user("test", "test")
except ValueError as e:
    print(e)
api.get_all_users()

2024-11-30 13:59:55.801 | INFO     | food_manager.api:get_all_users:66 - Retrieved all users from the database.

   id username                                    hashed_password
0   1     test  ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e47...

In [6]:
# api.set_current_user(username="test")

In [7]:
for i in range(10):
    api.add_food_item(name="apple", quantity=i + 1)

api.get_all_food_items()

NoResultFound: No row was found when one was required

In [ ]:
api.get_all_food_items()

2024-11-30 13:59:34.059 | INFO     | food_manager.api:get_all_food_items:197 - Retrieved all food items from the database.

   id   name  quantity                        date_added  user_id
0   1  apple         1  2024-11-30 12:59:10.083223+00:00        1
1   2  apple         2  2024-11-30 12:59:10.085721+00:00        1
2   3  apple         3  2024-11-30 12:59:10.087223+00:00        1
3   4  apple         4  2024-11-30 12:59:10.088721+00:00        1
4   5  apple         5  2024-11-30 12:59:10.089722+00:00        1
5   6  apple         6  2024-11-30 12:59:10.090721+00:00        1
6   7  apple         7  2024-11-30 12:59:10.091721+00:00        1
7   8  apple         8  2024-11-30 12:59:10.092720+00:00        1
8   9  apple         9  2024-11-30 12:59:10.093721+00:00        1
9  10  apple        10  2024-11-30 12:59:10.094721+00:00        1

In [ ]:
api.update_food_item_quantity(id=1, quantity=10)
api.get_all_food_items()

2024-11-30 13:59:43.551 | INFO     | food_manager.api:update_food_item_quantity:127 - Updated quantity of food item with id 1 to 10.
2024-11-30 13:59:43.555 | INFO     | food_manager.api:get_all_food_items:197 - Retrieved all food items from the database.

   id   name  quantity                        date_added  user_id
0   1  apple        10  2024-11-30 12:59:10.083223+00:00        1
1   2  apple         2  2024-11-30 12:59:10.085721+00:00        1
2   3  apple         3  2024-11-30 12:59:10.087223+00:00        1
3   4  apple         4  2024-11-30 12:59:10.088721+00:00        1
4   5  apple         5  2024-11-30 12:59:10.089722+00:00        1
5   6  apple         6  2024-11-30 12:59:10.090721+00:00        1
6   7  apple         7  2024-11-30 12:59:10.091721+00:00        1
7   8  apple         8  2024-11-30 12:59:10.092720+00:00        1
8   9  apple         9  2024-11-30 12:59:10.093721+00:00        1
9  10  apple        10  2024-11-30 12:59:10.094721+00:00        1